-- =====================================================================
-- V22: 设计图完整业务数据种子（幂等——全部按自然键判重，可重复执行）
-- 内容：部门树 / 岗位 / 角色 / 角色权限 / 员工花名册 / 人员角色 / 汇报线
-- 来源：docs/design/海峡金OA审批系统原型.html 的组织与花名册（40 人）
-- 注意：在已有数据的库上执行会自动跳过已存在行
-- =====================================================================

-- ---------- 1. 部门（12 个：总经办 + 5 中心 + 6 部门） ----------
INSERT INTO sys_department (name, parent_id, sort_order) SELECT '总经办', NULL, 1 WHERE NOT EXISTS (SELECT 1 FROM sys_department WHERE name = '总经办');
INSERT INTO sys_department (name, parent_id, sort_order) SELECT '财务中心', NULL, 2 WHERE NOT EXISTS (SELECT 1 FROM sys_department WHERE name = '财务中心');
INSERT INTO sys_department (name, parent_id, sort_order) SELECT '人力行政中心', NULL, 3 WHERE NOT EXISTS (SELECT 1 FROM sys_department WHERE name = '人力行政中心');
INSERT INTO sys_department (name, parent_id, sort_order) SELECT '业务支持中心', NULL, 4 WHERE NOT EXISTS (SELECT 1 FROM sys_department WHERE name = '业务支持中心');
INSERT INTO sys_department (name, parent_id, sort_order) SELECT '供应链中心', NULL, 5 WHERE NOT EXISTS (SELECT 1 FROM sys_department WHERE name = '供应链中心');
INSERT INTO sys_department (name, parent_id, sort_order) SELECT '资管中心', NULL, 6 WHERE NOT EXISTS (SELECT 1 FROM sys_department WHERE name = '资管中心');

INSERT INTO sys_department (name, parent_id, sort_order) SELECT '财务部', (SELECT id FROM sys_department WHERE name = '财务中心'), 0 WHERE NOT EXISTS (SELECT 1 FROM sys_department WHERE name = '财务部');
INSERT INTO sys_department (name, parent_id, sort_order) SELECT '内控部', (SELECT id FROM sys_department WHERE name = '总经办'), 0 WHERE NOT EXISTS (SELECT 1 FROM sys_department WHERE name = '内控部');
INSERT INTO sys_department (name, parent_id, sort_order) SELECT '法务部', (SELECT id FROM sys_department WHERE name = '总经办'), 0 WHERE NOT EXISTS (SELECT 1 FROM sys_department WHERE name = '法务部');
INSERT INTO sys_department (name, parent_id, sort_order) SELECT '行政部', (SELECT id FROM sys_department WHERE name = '人力行政中心'), 0 WHERE NOT EXISTS (SELECT 1 FROM sys_department WHERE name = '行政部');
INSERT INTO sys_department (name, parent_id, sort_order) SELECT '运营服务部', (SELECT id FROM sys_department WHERE name = '业务支持中心'), 0 WHERE NOT EXISTS (SELECT 1 FROM sys_department WHERE name = '运营服务部');
INSERT INTO sys_department (name, parent_id, sort_order) SELECT '交付部', (SELECT id FROM sys_department WHERE name = '供应链中心'), 0 WHERE NOT EXISTS (SELECT 1 FROM sys_department WHERE name = '交付部');

-- ---------- 2. 部门闭包补全（自环 + 父子，幂等） ----------
INSERT INTO sys_department_closure (ancestor_id, descendant_id, depth)
SELECT d.id, d.id, 0 FROM sys_department d
WHERE NOT EXISTS (SELECT 1 FROM sys_department_closure c WHERE c.ancestor_id = d.id AND c.descendant_id = d.id);

INSERT INTO sys_department_closure (ancestor_id, descendant_id, depth)
SELECT p.id, c.id, 1 FROM sys_department c JOIN sys_department p ON p.id = c.parent_id
WHERE NOT EXISTS (SELECT 1 FROM sys_department_closure c2 WHERE c2.ancestor_id = p.id AND c2.descendant_id = c.id);

-- ---------- 3. 岗位（全局职种库） ----------
INSERT INTO sys_post (name) SELECT '系统管理岗' WHERE NOT EXISTS (SELECT 1 FROM sys_post WHERE name = '系统管理岗');
INSERT INTO sys_post (name) SELECT '业务经理' WHERE NOT EXISTS (SELECT 1 FROM sys_post WHERE name = '业务经理');
INSERT INTO sys_post (name) SELECT '核算岗' WHERE NOT EXISTS (SELECT 1 FROM sys_post WHERE name = '核算岗');
INSERT INTO sys_post (name) SELECT '公司领导' WHERE NOT EXISTS (SELECT 1 FROM sys_post WHERE name = '公司领导');
INSERT INTO sys_post (name) SELECT '执行总经理' WHERE NOT EXISTS (SELECT 1 FROM sys_post WHERE name = '执行总经理');
INSERT INTO sys_post (name) SELECT '中心负责人' WHERE NOT EXISTS (SELECT 1 FROM sys_post WHERE name = '中心负责人');
INSERT INTO sys_post (name) SELECT '部门负责人' WHERE NOT EXISTS (SELECT 1 FROM sys_post WHERE name = '部门负责人');
INSERT INTO sys_post (name) SELECT '会计主管/内控' WHERE NOT EXISTS (SELECT 1 FROM sys_post WHERE name = '会计主管/内控');
INSERT INTO sys_post (name) SELECT '会计' WHERE NOT EXISTS (SELECT 1 FROM sys_post WHERE name = '会计');
INSERT INTO sys_post (name) SELECT '内控主管' WHERE NOT EXISTS (SELECT 1 FROM sys_post WHERE name = '内控主管');
INSERT INTO sys_post (name) SELECT '内控专员' WHERE NOT EXISTS (SELECT 1 FROM sys_post WHERE name = '内控专员');
INSERT INTO sys_post (name) SELECT '法务' WHERE NOT EXISTS (SELECT 1 FROM sys_post WHERE name = '法务');
INSERT INTO sys_post (name) SELECT '法务主管' WHERE NOT EXISTS (SELECT 1 FROM sys_post WHERE name = '法务主管');
INSERT INTO sys_post (name) SELECT '行政专员' WHERE NOT EXISTS (SELECT 1 FROM sys_post WHERE name = '行政专员');
INSERT INTO sys_post (name) SELECT '行政主管' WHERE NOT EXISTS (SELECT 1 FROM sys_post WHERE name = '行政主管');
INSERT INTO sys_post (name) SELECT '商务专员' WHERE NOT EXISTS (SELECT 1 FROM sys_post WHERE name = '商务专员');
INSERT INTO sys_post (name) SELECT '运营服务主管' WHERE NOT EXISTS (SELECT 1 FROM sys_post WHERE name = '运营服务主管');
INSERT INTO sys_post (name) SELECT '交付主管' WHERE NOT EXISTS (SELECT 1 FROM sys_post WHERE name = '交付主管');
INSERT INTO sys_post (name) SELECT '财务经理' WHERE NOT EXISTS (SELECT 1 FROM sys_post WHERE name = '财务经理');
INSERT INTO sys_post (name) SELECT '出纳主管' WHERE NOT EXISTS (SELECT 1 FROM sys_post WHERE name = '出纳主管');
INSERT INTO sys_post (name) SELECT '出纳' WHERE NOT EXISTS (SELECT 1 FROM sys_post WHERE name = '出纳');
INSERT INTO sys_post (name) SELECT '系统管理员' WHERE NOT EXISTS (SELECT 1 FROM sys_post WHERE name = '系统管理员');

-- ---------- 4. 角色（17 个，含归属部门/适用岗位/数据范围） ----------
INSERT INTO sys_role (name, department_id, post, data_scope_id) SELECT '超级管理员', (SELECT id FROM sys_department WHERE name = '总经办'), '系统管理岗', (SELECT id FROM sys_data_scope WHERE code = 'ALL') WHERE NOT EXISTS (SELECT 1 FROM sys_role WHERE name = '超级管理员');
INSERT INTO sys_role (name, department_id, post, data_scope_id) SELECT '一级中心负责人', (SELECT id FROM sys_department WHERE name = '总经办'), '中心负责人', (SELECT id FROM sys_data_scope WHERE code = 'DEPT_AND_CHILD') WHERE NOT EXISTS (SELECT 1 FROM sys_role WHERE name = '一级中心负责人');
INSERT INTO sys_role (name, department_id, post, data_scope_id) SELECT '二级部门负责人', (SELECT id FROM sys_department WHERE name = '总经办'), '部门负责人', (SELECT id FROM sys_data_scope WHERE code = 'DEPT') WHERE NOT EXISTS (SELECT 1 FROM sys_role WHERE name = '二级部门负责人');
INSERT INTO sys_role (name, department_id, post, data_scope_id) SELECT '交付主管', (SELECT id FROM sys_department WHERE name = '交付部'), '交付主管', (SELECT id FROM sys_data_scope WHERE code = 'ALL') WHERE NOT EXISTS (SELECT 1 FROM sys_role WHERE name = '交付主管');
INSERT INTO sys_role (name, department_id, post, data_scope_id) SELECT '会计主管&内控', (SELECT id FROM sys_department WHERE name = '财务中心'), '会计主管/内控', (SELECT id FROM sys_data_scope WHERE code = 'ALL') WHERE NOT EXISTS (SELECT 1 FROM sys_role WHERE name = '会计主管&内控');
INSERT INTO sys_role (name, department_id, post, data_scope_id) SELECT '公司领导', (SELECT id FROM sys_department WHERE name = '总经办'), '公司领导', (SELECT id FROM sys_data_scope WHERE code = 'ALL') WHERE NOT EXISTS (SELECT 1 FROM sys_role WHERE name = '公司领导');
INSERT INTO sys_role (name, department_id, post, data_scope_id) SELECT '内控专员', (SELECT id FROM sys_department WHERE name = '内控部'), '内控专员', (SELECT id FROM sys_data_scope WHERE code = 'OWN') WHERE NOT EXISTS (SELECT 1 FROM sys_role WHERE name = '内控专员');
INSERT INTO sys_role (name, department_id, post, data_scope_id) SELECT '内控主管', (SELECT id FROM sys_department WHERE name = '内控部'), '内控主管', (SELECT id FROM sys_data_scope WHERE code = 'ALL') WHERE NOT EXISTS (SELECT 1 FROM sys_role WHERE name = '内控主管');
INSERT INTO sys_role (name, department_id, post, data_scope_id) SELECT '出纳', (SELECT id FROM sys_department WHERE name = '资管中心'), '出纳', (SELECT id FROM sys_data_scope WHERE code = 'ALL') WHERE NOT EXISTS (SELECT 1 FROM sys_role WHERE name = '出纳');
INSERT INTO sys_role (name, department_id, post, data_scope_id) SELECT '出纳主管', (SELECT id FROM sys_department WHERE name = '资管中心'), '出纳主管', (SELECT id FROM sys_data_scope WHERE code = 'ALL') WHERE NOT EXISTS (SELECT 1 FROM sys_role WHERE name = '出纳主管');
INSERT INTO sys_role (name, department_id, post, data_scope_id) SELECT '商务专员', (SELECT id FROM sys_department WHERE name = '运营服务部'), '商务专员', (SELECT id FROM sys_data_scope WHERE code = 'ALL') WHERE NOT EXISTS (SELECT 1 FROM sys_role WHERE name = '商务专员');
INSERT INTO sys_role (name, department_id, post, data_scope_id) SELECT '执行总经理', (SELECT id FROM sys_department WHERE name = '总经办'), '执行总经理', (SELECT id FROM sys_data_scope WHERE code = 'ALL') WHERE NOT EXISTS (SELECT 1 FROM sys_role WHERE name = '执行总经理');
INSERT INTO sys_role (name, department_id, post, data_scope_id) SELECT '核算会计', (SELECT id FROM sys_department WHERE name = '财务部'), '会计', (SELECT id FROM sys_data_scope WHERE code = 'DEPT') WHERE NOT EXISTS (SELECT 1 FROM sys_role WHERE name = '核算会计');
INSERT INTO sys_role (name, department_id, post, data_scope_id) SELECT '法务', (SELECT id FROM sys_department WHERE name = '法务部'), '法务', (SELECT id FROM sys_data_scope WHERE code = 'OWN') WHERE NOT EXISTS (SELECT 1 FROM sys_role WHERE name = '法务');
INSERT INTO sys_role (name, department_id, post, data_scope_id) SELECT '法务主管', (SELECT id FROM sys_department WHERE name = '法务部'), '法务主管', (SELECT id FROM sys_data_scope WHERE code = 'OWN') WHERE NOT EXISTS (SELECT 1 FROM sys_role WHERE name = '法务主管');
INSERT INTO sys_role (name, department_id, post, data_scope_id) SELECT '行政专员', (SELECT id FROM sys_department WHERE name = '行政部'), '行政专员', (SELECT id FROM sys_data_scope WHERE code = 'OWN') WHERE NOT EXISTS (SELECT 1 FROM sys_role WHERE name = '行政专员');
INSERT INTO sys_role (name, department_id, post, data_scope_id) SELECT '行政主管', (SELECT id FROM sys_department WHERE name = '行政部'), '行政主管', (SELECT id FROM sys_data_scope WHERE code = 'OWN') WHERE NOT EXISTS (SELECT 1 FROM sys_role WHERE name = '行政主管');
INSERT INTO sys_role (name, department_id, post, data_scope_id) SELECT '财务经理', (SELECT id FROM sys_department WHERE name = '财务部'), '财务经理', (SELECT id FROM sys_data_scope WHERE code = 'ALL') WHERE NOT EXISTS (SELECT 1 FROM sys_role WHERE name = '财务经理');
INSERT INTO sys_role (name, department_id, post, data_scope_id) SELECT '运营服务主管', (SELECT id FROM sys_department WHERE name = '运营服务部'), '运营服务主管', (SELECT id FROM sys_data_scope WHERE code = 'ALL') WHERE NOT EXISTS (SELECT 1 FROM sys_role WHERE name = '运营服务主管');

-- ---------- 5. 角色权限（4 个真开关按设计分配） ----------
INSERT INTO sys_role_permission (role_id, permission_id) SELECT r.id, p.id FROM sys_role r JOIN sys_permission p ON p.code = 'VIEW_OWN_FORMS' WHERE r.name = '超级管理员' AND NOT EXISTS (SELECT 1 FROM sys_role_permission rp WHERE rp.role_id = r.id AND rp.permission_id = p.id);
INSERT INTO sys_role_permission (role_id, permission_id) SELECT r.id, p.id FROM sys_role r JOIN sys_permission p ON p.code = 'SUBMIT_ALL_FORMS' WHERE r.name = '超级管理员' AND NOT EXISTS (SELECT 1 FROM sys_role_permission rp WHERE rp.role_id = r.id AND rp.permission_id = p.id);
INSERT INTO sys_role_permission (role_id, permission_id) SELECT r.id, p.id FROM sys_role r JOIN sys_permission p ON p.code = 'APPROVE_ALL_NODES' WHERE r.name = '超级管理员' AND NOT EXISTS (SELECT 1 FROM sys_role_permission rp WHERE rp.role_id = r.id AND rp.permission_id = p.id);
INSERT INTO sys_role_permission (role_id, permission_id) SELECT r.id, p.id FROM sys_role r JOIN sys_permission p ON p.code = 'CONFIGURE_FLOW_PERMISSION' WHERE r.name = '超级管理员' AND NOT EXISTS (SELECT 1 FROM sys_role_permission rp WHERE rp.role_id = r.id AND rp.permission_id = p.id);
INSERT INTO sys_role_permission (role_id, permission_id) SELECT r.id, p.id FROM sys_role r JOIN sys_permission p ON p.code = 'VIEW_OWN_FORMS' WHERE r.name = '一级中心负责人' AND NOT EXISTS (SELECT 1 FROM sys_role_permission rp WHERE rp.role_id = r.id AND rp.permission_id = p.id);
INSERT INTO sys_role_permission (role_id, permission_id) SELECT r.id, p.id FROM sys_role r JOIN sys_permission p ON p.code = 'SUBMIT_ALL_FORMS' WHERE r.name = '一级中心负责人' AND NOT EXISTS (SELECT 1 FROM sys_role_permission rp WHERE rp.role_id = r.id AND rp.permission_id = p.id);
INSERT INTO sys_role_permission (role_id, permission_id) SELECT r.id, p.id FROM sys_role r JOIN sys_permission p ON p.code = 'VIEW_OWN_FORMS' WHERE r.name = '二级部门负责人' AND NOT EXISTS (SELECT 1 FROM sys_role_permission rp WHERE rp.role_id = r.id AND rp.permission_id = p.id);
INSERT INTO sys_role_permission (role_id, permission_id) SELECT r.id, p.id FROM sys_role r JOIN sys_permission p ON p.code = 'SUBMIT_ALL_FORMS' WHERE r.name = '二级部门负责人' AND NOT EXISTS (SELECT 1 FROM sys_role_permission rp WHERE rp.role_id = r.id AND rp.permission_id = p.id);
INSERT INTO sys_role_permission (role_id, permission_id) SELECT r.id, p.id FROM sys_role r JOIN sys_permission p ON p.code = 'VIEW_OWN_FORMS' WHERE r.name = '交付主管' AND NOT EXISTS (SELECT 1 FROM sys_role_permission rp WHERE rp.role_id = r.id AND rp.permission_id = p.id);
INSERT INTO sys_role_permission (role_id, permission_id) SELECT r.id, p.id FROM sys_role r JOIN sys_permission p ON p.code = 'SUBMIT_ALL_FORMS' WHERE r.name = '交付主管' AND NOT EXISTS (SELECT 1 FROM sys_role_permission rp WHERE rp.role_id = r.id AND rp.permission_id = p.id);
INSERT INTO sys_role_permission (role_id, permission_id) SELECT r.id, p.id FROM sys_role r JOIN sys_permission p ON p.code = 'VIEW_OWN_FORMS' WHERE r.name = '会计主管&内控' AND NOT EXISTS (SELECT 1 FROM sys_role_permission rp WHERE rp.role_id = r.id AND rp.permission_id = p.id);
INSERT INTO sys_role_permission (role_id, permission_id) SELECT r.id, p.id FROM sys_role r JOIN sys_permission p ON p.code = 'SUBMIT_ALL_FORMS' WHERE r.name = '会计主管&内控' AND NOT EXISTS (SELECT 1 FROM sys_role_permission rp WHERE rp.role_id = r.id AND rp.permission_id = p.id);
INSERT INTO sys_role_permission (role_id, permission_id) SELECT r.id, p.id FROM sys_role r JOIN sys_permission p ON p.code = 'VIEW_OWN_FORMS' WHERE r.name = '公司领导' AND NOT EXISTS (SELECT 1 FROM sys_role_permission rp WHERE rp.role_id = r.id AND rp.permission_id = p.id);
INSERT INTO sys_role_permission (role_id, permission_id) SELECT r.id, p.id FROM sys_role r JOIN sys_permission p ON p.code = 'SUBMIT_ALL_FORMS' WHERE r.name = '公司领导' AND NOT EXISTS (SELECT 1 FROM sys_role_permission rp WHERE rp.role_id = r.id AND rp.permission_id = p.id);
INSERT INTO sys_role_permission (role_id, permission_id) SELECT r.id, p.id FROM sys_role r JOIN sys_permission p ON p.code = 'VIEW_OWN_FORMS' WHERE r.name = '内控专员' AND NOT EXISTS (SELECT 1 FROM sys_role_permission rp WHERE rp.role_id = r.id AND rp.permission_id = p.id);
INSERT INTO sys_role_permission (role_id, permission_id) SELECT r.id, p.id FROM sys_role r JOIN sys_permission p ON p.code = 'SUBMIT_ALL_FORMS' WHERE r.name = '内控专员' AND NOT EXISTS (SELECT 1 FROM sys_role_permission rp WHERE rp.role_id = r.id AND rp.permission_id = p.id);
INSERT INTO sys_role_permission (role_id, permission_id) SELECT r.id, p.id FROM sys_role r JOIN sys_permission p ON p.code = 'VIEW_OWN_FORMS' WHERE r.name = '内控主管' AND NOT EXISTS (SELECT 1 FROM sys_role_permission rp WHERE rp.role_id = r.id AND rp.permission_id = p.id);
INSERT INTO sys_role_permission (role_id, permission_id) SELECT r.id, p.id FROM sys_role r JOIN sys_permission p ON p.code = 'SUBMIT_ALL_FORMS' WHERE r.name = '内控主管' AND NOT EXISTS (SELECT 1 FROM sys_role_permission rp WHERE rp.role_id = r.id AND rp.permission_id = p.id);
INSERT INTO sys_role_permission (role_id, permission_id) SELECT r.id, p.id FROM sys_role r JOIN sys_permission p ON p.code = 'VIEW_OWN_FORMS' WHERE r.name = '出纳' AND NOT EXISTS (SELECT 1 FROM sys_role_permission rp WHERE rp.role_id = r.id AND rp.permission_id = p.id);
INSERT INTO sys_role_permission (role_id, permission_id) SELECT r.id, p.id FROM sys_role r JOIN sys_permission p ON p.code = 'SUBMIT_ALL_FORMS' WHERE r.name = '出纳' AND NOT EXISTS (SELECT 1 FROM sys_role_permission rp WHERE rp.role_id = r.id AND rp.permission_id = p.id);
INSERT INTO sys_role_permission (role_id, permission_id) SELECT r.id, p.id FROM sys_role r JOIN sys_permission p ON p.code = 'VIEW_OWN_FORMS' WHERE r.name = '出纳主管' AND NOT EXISTS (SELECT 1 FROM sys_role_permission rp WHERE rp.role_id = r.id AND rp.permission_id = p.id);
INSERT INTO sys_role_permission (role_id, permission_id) SELECT r.id, p.id FROM sys_role r JOIN sys_permission p ON p.code = 'SUBMIT_ALL_FORMS' WHERE r.name = '出纳主管' AND NOT EXISTS (SELECT 1 FROM sys_role_permission rp WHERE rp.role_id = r.id AND rp.permission_id = p.id);
INSERT INTO sys_role_permission (role_id, permission_id) SELECT r.id, p.id FROM sys_role r JOIN sys_permission p ON p.code = 'VIEW_OWN_FORMS' WHERE r.name = '商务专员' AND NOT EXISTS (SELECT 1 FROM sys_role_permission rp WHERE rp.role_id = r.id AND rp.permission_id = p.id);
INSERT INTO sys_role_permission (role_id, permission_id) SELECT r.id, p.id FROM sys_role r JOIN sys_permission p ON p.code = 'SUBMIT_ALL_FORMS' WHERE r.name = '商务专员' AND NOT EXISTS (SELECT 1 FROM sys_role_permission rp WHERE rp.role_id = r.id AND rp.permission_id = p.id);
INSERT INTO sys_role_permission (role_id, permission_id) SELECT r.id, p.id FROM sys_role r JOIN sys_permission p ON p.code = 'VIEW_OWN_FORMS' WHERE r.name = '执行总经理' AND NOT EXISTS (SELECT 1 FROM sys_role_permission rp WHERE rp.role_id = r.id AND rp.permission_id = p.id);
INSERT INTO sys_role_permission (role_id, permission_id) SELECT r.id, p.id FROM sys_role r JOIN sys_permission p ON p.code = 'SUBMIT_ALL_FORMS' WHERE r.name = '执行总经理' AND NOT EXISTS (SELECT 1 FROM sys_role_permission rp WHERE rp.role_id = r.id AND rp.permission_id = p.id);
INSERT INTO sys_role_permission (role_id, permission_id) SELECT r.id, p.id FROM sys_role r JOIN sys_permission p ON p.code = 'VIEW_OWN_FORMS' WHERE r.name = '核算会计' AND NOT EXISTS (SELECT 1 FROM sys_role_permission rp WHERE rp.role_id = r.id AND rp.permission_id = p.id);
INSERT INTO sys_role_permission (role_id, permission_id) SELECT r.id, p.id FROM sys_role r JOIN sys_permission p ON p.code = 'SUBMIT_ALL_FORMS' WHERE r.name = '核算会计' AND NOT EXISTS (SELECT 1 FROM sys_role_permission rp WHERE rp.role_id = r.id AND rp.permission_id = p.id);
INSERT INTO sys_role_permission (role_id, permission_id) SELECT r.id, p.id FROM sys_role r JOIN sys_permission p ON p.code = 'VIEW_OWN_FORMS' WHERE r.name = '法务' AND NOT EXISTS (SELECT 1 FROM sys_role_permission rp WHERE rp.role_id = r.id AND rp.permission_id = p.id);
INSERT INTO sys_role_permission (role_id, permission_id) SELECT r.id, p.id FROM sys_role r JOIN sys_permission p ON p.code = 'SUBMIT_ALL_FORMS' WHERE r.name = '法务' AND NOT EXISTS (SELECT 1 FROM sys_role_permission rp WHERE rp.role_id = r.id AND rp.permission_id = p.id);
INSERT INTO sys_role_permission (role_id, permission_id) SELECT r.id, p.id FROM sys_role r JOIN sys_permission p ON p.code = 'VIEW_OWN_FORMS' WHERE r.name = '法务主管' AND NOT EXISTS (SELECT 1 FROM sys_role_permission rp WHERE rp.role_id = r.id AND rp.permission_id = p.id);
INSERT INTO sys_role_permission (role_id, permission_id) SELECT r.id, p.id FROM sys_role r JOIN sys_permission p ON p.code = 'SUBMIT_ALL_FORMS' WHERE r.name = '法务主管' AND NOT EXISTS (SELECT 1 FROM sys_role_permission rp WHERE rp.role_id = r.id AND rp.permission_id = p.id);
INSERT INTO sys_role_permission (role_id, permission_id) SELECT r.id, p.id FROM sys_role r JOIN sys_permission p ON p.code = 'VIEW_OWN_FORMS' WHERE r.name = '行政专员' AND NOT EXISTS (SELECT 1 FROM sys_role_permission rp WHERE rp.role_id = r.id AND rp.permission_id = p.id);
INSERT INTO sys_role_permission (role_id, permission_id) SELECT r.id, p.id FROM sys_role r JOIN sys_permission p ON p.code = 'SUBMIT_ALL_FORMS' WHERE r.name = '行政专员' AND NOT EXISTS (SELECT 1 FROM sys_role_permission rp WHERE rp.role_id = r.id AND rp.permission_id = p.id);
INSERT INTO sys_role_permission (role_id, permission_id) SELECT r.id, p.id FROM sys_role r JOIN sys_permission p ON p.code = 'VIEW_OWN_FORMS' WHERE r.name = '行政主管' AND NOT EXISTS (SELECT 1 FROM sys_role_permission rp WHERE rp.role_id = r.id AND rp.permission_id = p.id);
INSERT INTO sys_role_permission (role_id, permission_id) SELECT r.id, p.id FROM sys_role r JOIN sys_permission p ON p.code = 'SUBMIT_ALL_FORMS' WHERE r.name = '行政主管' AND NOT EXISTS (SELECT 1 FROM sys_role_permission rp WHERE rp.role_id = r.id AND rp.permission_id = p.id);
INSERT INTO sys_role_permission (role_id, permission_id) SELECT r.id, p.id FROM sys_role r JOIN sys_permission p ON p.code = 'VIEW_OWN_FORMS' WHERE r.name = '财务经理' AND NOT EXISTS (SELECT 1 FROM sys_role_permission rp WHERE rp.role_id = r.id AND rp.permission_id = p.id);
INSERT INTO sys_role_permission (role_id, permission_id) SELECT r.id, p.id FROM sys_role r JOIN sys_permission p ON p.code = 'SUBMIT_ALL_FORMS' WHERE r.name = '财务经理' AND NOT EXISTS (SELECT 1 FROM sys_role_permission rp WHERE rp.role_id = r.id AND rp.permission_id = p.id);
INSERT INTO sys_role_permission (role_id, permission_id) SELECT r.id, p.id FROM sys_role r JOIN sys_permission p ON p.code = 'VIEW_OWN_FORMS' WHERE r.name = '运营服务主管' AND NOT EXISTS (SELECT 1 FROM sys_role_permission rp WHERE rp.role_id = r.id AND rp.permission_id = p.id);
INSERT INTO sys_role_permission (role_id, permission_id) SELECT r.id, p.id FROM sys_role r JOIN sys_permission p ON p.code = 'SUBMIT_ALL_FORMS' WHERE r.name = '运营服务主管' AND NOT EXISTS (SELECT 1 FROM sys_role_permission rp WHERE rp.role_id = r.id AND rp.permission_id = p.id);

-- ---------- 6. 员工花名册（40 人，密码统一 password） ----------
INSERT INTO sys_user (job_no, name, account, password, department_id, post_id, status) SELECT 'HXJ000', '超级管理员', 'admin', '$2y$10$eWcufB2byZqOZspjH6UaO.4PKvivPpotPILxGL1LscJspy4a5t0VW', (SELECT id FROM sys_department WHERE name = '总经办'), (SELECT id FROM sys_post WHERE name = '系统管理岗'), 'ACTIVE' WHERE NOT EXISTS (SELECT 1 FROM sys_user WHERE account = 'admin');
INSERT INTO sys_user (job_no, name, account, password, department_id, post_id, status) SELECT 'HXJ001', '林安然', 'linanran', '$2y$10$eWcufB2byZqOZspjH6UaO.4PKvivPpotPILxGL1LscJspy4a5t0VW', (SELECT id FROM sys_department WHERE name = '总经办'), (SELECT id FROM sys_post WHERE name = '系统管理员'), 'ACTIVE' WHERE NOT EXISTS (SELECT 1 FROM sys_user WHERE account = 'linanran');
INSERT INTO sys_user (job_no, name, account, password, department_id, post_id, status) SELECT 'HXJ002', '连力', 'lianli', '$2y$10$eWcufB2byZqOZspjH6UaO.4PKvivPpotPILxGL1LscJspy4a5t0VW', (SELECT id FROM sys_department WHERE name = '总经办'), (SELECT id FROM sys_post WHERE name = '公司领导'), 'ACTIVE' WHERE NOT EXISTS (SELECT 1 FROM sys_user WHERE account = 'lianli');
INSERT INTO sys_user (job_no, name, account, password, department_id, post_id, status) SELECT 'HXJ003', '王强', 'wangqiang', '$2y$10$eWcufB2byZqOZspjH6UaO.4PKvivPpotPILxGL1LscJspy4a5t0VW', (SELECT id FROM sys_department WHERE name = '总经办'), (SELECT id FROM sys_post WHERE name = '公司领导'), 'ACTIVE' WHERE NOT EXISTS (SELECT 1 FROM sys_user WHERE account = 'wangqiang');
INSERT INTO sys_user (job_no, name, account, password, department_id, post_id, status) SELECT 'HXJ004', '舒飞', 'shufei', '$2y$10$eWcufB2byZqOZspjH6UaO.4PKvivPpotPILxGL1LscJspy4a5t0VW', (SELECT id FROM sys_department WHERE name = '业务支持中心'), (SELECT id FROM sys_post WHERE name = '中心负责人'), 'ACTIVE' WHERE NOT EXISTS (SELECT 1 FROM sys_user WHERE account = 'shufei');
INSERT INTO sys_user (job_no, name, account, password, department_id, post_id, status) SELECT 'HXJ005', '卢乙芬', 'luyifen', '$2y$10$eWcufB2byZqOZspjH6UaO.4PKvivPpotPILxGL1LscJspy4a5t0VW', (SELECT id FROM sys_department WHERE name = '人力行政中心'), (SELECT id FROM sys_post WHERE name = '中心负责人'), 'ACTIVE' WHERE NOT EXISTS (SELECT 1 FROM sys_user WHERE account = 'luyifen');
INSERT INTO sys_user (job_no, name, account, password, department_id, post_id, status) SELECT 'HXJ006', '刘婷', 'liuting', '$2y$10$eWcufB2byZqOZspjH6UaO.4PKvivPpotPILxGL1LscJspy4a5t0VW', (SELECT id FROM sys_department WHERE name = '资管中心'), (SELECT id FROM sys_post WHERE name = '出纳主管'), 'ACTIVE' WHERE NOT EXISTS (SELECT 1 FROM sys_user WHERE account = 'liuting');
INSERT INTO sys_user (job_no, name, account, password, department_id, post_id, status) SELECT 'HXJ007', '王海亮', 'wanghailiang', '$2y$10$eWcufB2byZqOZspjH6UaO.4PKvivPpotPILxGL1LscJspy4a5t0VW', (SELECT id FROM sys_department WHERE name = '供应链中心'), (SELECT id FROM sys_post WHERE name = '中心负责人'), 'ACTIVE' WHERE NOT EXISTS (SELECT 1 FROM sys_user WHERE account = 'wanghailiang');
INSERT INTO sys_user (job_no, name, account, password, department_id, post_id, status) SELECT 'HXJ008', '张龙', 'zhanglong', '$2y$10$eWcufB2byZqOZspjH6UaO.4PKvivPpotPILxGL1LscJspy4a5t0VW', (SELECT id FROM sys_department WHERE name = '交付部'), (SELECT id FROM sys_post WHERE name = '交付主管'), 'ACTIVE' WHERE NOT EXISTS (SELECT 1 FROM sys_user WHERE account = 'zhanglong');
INSERT INTO sys_user (job_no, name, account, password, department_id, post_id, status) SELECT 'HXJ009', '刘佳慧', 'liujiahui', '$2y$10$eWcufB2byZqOZspjH6UaO.4PKvivPpotPILxGL1LscJspy4a5t0VW', (SELECT id FROM sys_department WHERE name = '行政部'), (SELECT id FROM sys_post WHERE name = '行政主管'), 'ACTIVE' WHERE NOT EXISTS (SELECT 1 FROM sys_user WHERE account = 'liujiahui');
INSERT INTO sys_user (job_no, name, account, password, department_id, post_id, status) SELECT 'HXJ010', '陈成辉', 'chenchenghui', '$2y$10$eWcufB2byZqOZspjH6UaO.4PKvivPpotPILxGL1LscJspy4a5t0VW', (SELECT id FROM sys_department WHERE name = '财务部'), (SELECT id FROM sys_post WHERE name = '部门负责人'), 'ACTIVE' WHERE NOT EXISTS (SELECT 1 FROM sys_user WHERE account = 'chenchenghui');
INSERT INTO sys_user (job_no, name, account, password, department_id, post_id, status) SELECT 'HXJ011', '郭静宇', 'guojingyu', '$2y$10$eWcufB2byZqOZspjH6UaO.4PKvivPpotPILxGL1LscJspy4a5t0VW', (SELECT id FROM sys_department WHERE name = '行政部'), (SELECT id FROM sys_post WHERE name = '部门负责人'), 'ACTIVE' WHERE NOT EXISTS (SELECT 1 FROM sys_user WHERE account = 'guojingyu');
INSERT INTO sys_user (job_no, name, account, password, department_id, post_id, status) SELECT 'HXJ012', '吴荷珍', 'wuhezhen', '$2y$10$eWcufB2byZqOZspjH6UaO.4PKvivPpotPILxGL1LscJspy4a5t0VW', (SELECT id FROM sys_department WHERE name = '财务部'), (SELECT id FROM sys_post WHERE name = '财务经理'), 'ACTIVE' WHERE NOT EXISTS (SELECT 1 FROM sys_user WHERE account = 'wuhezhen');
INSERT INTO sys_user (job_no, name, account, password, department_id, post_id, status) SELECT 'HXJ013', '王莹', 'wangying', '$2y$10$eWcufB2byZqOZspjH6UaO.4PKvivPpotPILxGL1LscJspy4a5t0VW', (SELECT id FROM sys_department WHERE name = '运营服务部'), (SELECT id FROM sys_post WHERE name = '部门负责人'), 'ACTIVE' WHERE NOT EXISTS (SELECT 1 FROM sys_user WHERE account = 'wangying');
INSERT INTO sys_user (job_no, name, account, password, department_id, post_id, status) SELECT 'HXJ014', '黄政哲', 'huangzhengzhe', '$2y$10$eWcufB2byZqOZspjH6UaO.4PKvivPpotPILxGL1LscJspy4a5t0VW', (SELECT id FROM sys_department WHERE name = '运营服务部'), (SELECT id FROM sys_post WHERE name = '运营服务主管'), 'ACTIVE' WHERE NOT EXISTS (SELECT 1 FROM sys_user WHERE account = 'huangzhengzhe');
INSERT INTO sys_user (job_no, name, account, password, department_id, post_id, status) SELECT 'HXJ015', '李林华', 'lilinhua', '$2y$10$eWcufB2byZqOZspjH6UaO.4PKvivPpotPILxGL1LscJspy4a5t0VW', (SELECT id FROM sys_department WHERE name = '交付部'), (SELECT id FROM sys_post WHERE name = '部门负责人'), 'ACTIVE' WHERE NOT EXISTS (SELECT 1 FROM sys_user WHERE account = 'lilinhua');
INSERT INTO sys_user (job_no, name, account, password, department_id, post_id, status) SELECT 'HXJ016', '苗福鑫', 'miaofuxin', '$2y$10$eWcufB2byZqOZspjH6UaO.4PKvivPpotPILxGL1LscJspy4a5t0VW', (SELECT id FROM sys_department WHERE name = '内控部'), (SELECT id FROM sys_post WHERE name = '部门负责人'), 'ACTIVE' WHERE NOT EXISTS (SELECT 1 FROM sys_user WHERE account = 'miaofuxin');
INSERT INTO sys_user (job_no, name, account, password, department_id, post_id, status) SELECT 'HXJ017', '翁建发', 'wengjianfa', '$2y$10$eWcufB2byZqOZspjH6UaO.4PKvivPpotPILxGL1LscJspy4a5t0VW', (SELECT id FROM sys_department WHERE name = '法务部'), (SELECT id FROM sys_post WHERE name = '部门负责人'), 'ACTIVE' WHERE NOT EXISTS (SELECT 1 FROM sys_user WHERE account = 'wengjianfa');
INSERT INTO sys_user (job_no, name, account, password, department_id, post_id, status) SELECT 'HXJ018', '汪洋', 'wangyang', '$2y$10$eWcufB2byZqOZspjH6UaO.4PKvivPpotPILxGL1LscJspy4a5t0VW', (SELECT id FROM sys_department WHERE name = '财务中心'), (SELECT id FROM sys_post WHERE name = '会计主管/内控'), 'ACTIVE' WHERE NOT EXISTS (SELECT 1 FROM sys_user WHERE account = 'wangyang');
INSERT INTO sys_user (job_no, name, account, password, department_id, post_id, status) SELECT 'HXJ019', '姚志豪', 'yaozhihao', '$2y$10$eWcufB2byZqOZspjH6UaO.4PKvivPpotPILxGL1LscJspy4a5t0VW', (SELECT id FROM sys_department WHERE name = '财务中心'), (SELECT id FROM sys_post WHERE name = '会计主管/内控'), 'ACTIVE' WHERE NOT EXISTS (SELECT 1 FROM sys_user WHERE account = 'yaozhihao');
INSERT INTO sys_user (job_no, name, account, password, department_id, post_id, status) SELECT 'HXJ020', '翁婷婷', 'wengtingting', '$2y$10$eWcufB2byZqOZspjH6UaO.4PKvivPpotPILxGL1LscJspy4a5t0VW', (SELECT id FROM sys_department WHERE name = '财务中心'), (SELECT id FROM sys_post WHERE name = '会计主管/内控'), 'ACTIVE' WHERE NOT EXISTS (SELECT 1 FROM sys_user WHERE account = 'wengtingting');
INSERT INTO sys_user (job_no, name, account, password, department_id, post_id, status) SELECT 'HXJ021', '冯训漪', 'fengxunyi', '$2y$10$eWcufB2byZqOZspjH6UaO.4PKvivPpotPILxGL1LscJspy4a5t0VW', (SELECT id FROM sys_department WHERE name = '财务部'), (SELECT id FROM sys_post WHERE name = '会计'), 'ACTIVE' WHERE NOT EXISTS (SELECT 1 FROM sys_user WHERE account = 'fengxunyi');
INSERT INTO sys_user (job_no, name, account, password, department_id, post_id, status) SELECT 'HXJ022', '朱昀怡', 'zhuyunyi', '$2y$10$eWcufB2byZqOZspjH6UaO.4PKvivPpotPILxGL1LscJspy4a5t0VW', (SELECT id FROM sys_department WHERE name = '财务部'), (SELECT id FROM sys_post WHERE name = '会计'), 'ACTIVE' WHERE NOT EXISTS (SELECT 1 FROM sys_user WHERE account = 'zhuyunyi');
INSERT INTO sys_user (job_no, name, account, password, department_id, post_id, status) SELECT 'HXJ023', '施惠君', 'shihuijun', '$2y$10$eWcufB2byZqOZspjH6UaO.4PKvivPpotPILxGL1LscJspy4a5t0VW', (SELECT id FROM sys_department WHERE name = '财务部'), (SELECT id FROM sys_post WHERE name = '会计'), 'ACTIVE' WHERE NOT EXISTS (SELECT 1 FROM sys_user WHERE account = 'shihuijun');
INSERT INTO sys_user (job_no, name, account, password, department_id, post_id, status) SELECT 'HXJ024', '蔡赐绵', 'caicimian', '$2y$10$eWcufB2byZqOZspjH6UaO.4PKvivPpotPILxGL1LscJspy4a5t0VW', (SELECT id FROM sys_department WHERE name = '财务部'), (SELECT id FROM sys_post WHERE name = '会计'), 'ACTIVE' WHERE NOT EXISTS (SELECT 1 FROM sys_user WHERE account = 'caicimian');
INSERT INTO sys_user (job_no, name, account, password, department_id, post_id, status) SELECT 'HXJ025', '李小妹', 'lixiaomei', '$2y$10$eWcufB2byZqOZspjH6UaO.4PKvivPpotPILxGL1LscJspy4a5t0VW', (SELECT id FROM sys_department WHERE name = '财务部'), (SELECT id FROM sys_post WHERE name = '会计'), 'ACTIVE' WHERE NOT EXISTS (SELECT 1 FROM sys_user WHERE account = 'lixiaomei');
INSERT INTO sys_user (job_no, name, account, password, department_id, post_id, status) SELECT 'HXJ026', '石瀚文', 'shihanwen', '$2y$10$eWcufB2byZqOZspjH6UaO.4PKvivPpotPILxGL1LscJspy4a5t0VW', (SELECT id FROM sys_department WHERE name = '财务部'), (SELECT id FROM sys_post WHERE name = '会计'), 'ACTIVE' WHERE NOT EXISTS (SELECT 1 FROM sys_user WHERE account = 'shihanwen');
INSERT INTO sys_user (job_no, name, account, password, department_id, post_id, status) SELECT 'HXJ027', '张欣怡', 'zhangxinyi', '$2y$10$eWcufB2byZqOZspjH6UaO.4PKvivPpotPILxGL1LscJspy4a5t0VW', (SELECT id FROM sys_department WHERE name = '财务部'), (SELECT id FROM sys_post WHERE name = '会计'), 'ACTIVE' WHERE NOT EXISTS (SELECT 1 FROM sys_user WHERE account = 'zhangxinyi');
INSERT INTO sys_user (job_no, name, account, password, department_id, post_id, status) SELECT 'HXJ028', '温超群', 'wenchaoqun', '$2y$10$eWcufB2byZqOZspjH6UaO.4PKvivPpotPILxGL1LscJspy4a5t0VW', (SELECT id FROM sys_department WHERE name = '财务部'), (SELECT id FROM sys_post WHERE name = '会计'), 'ACTIVE' WHERE NOT EXISTS (SELECT 1 FROM sys_user WHERE account = 'wenchaoqun');
INSERT INTO sys_user (job_no, name, account, password, department_id, post_id, status) SELECT 'HXJ029', '孙倩倩', 'sunqianqian', '$2y$10$eWcufB2byZqOZspjH6UaO.4PKvivPpotPILxGL1LscJspy4a5t0VW', (SELECT id FROM sys_department WHERE name = '内控部'), (SELECT id FROM sys_post WHERE name = '内控主管'), 'ACTIVE' WHERE NOT EXISTS (SELECT 1 FROM sys_user WHERE account = 'sunqianqian');
INSERT INTO sys_user (job_no, name, account, password, department_id, post_id, status) SELECT 'HXJ030', '郑宁静', 'zhengningjing', '$2y$10$eWcufB2byZqOZspjH6UaO.4PKvivPpotPILxGL1LscJspy4a5t0VW', (SELECT id FROM sys_department WHERE name = '内控部'), (SELECT id FROM sys_post WHERE name = '内控专员'), 'ACTIVE' WHERE NOT EXISTS (SELECT 1 FROM sys_user WHERE account = 'zhengningjing');
INSERT INTO sys_user (job_no, name, account, password, department_id, post_id, status) SELECT 'HXJ031', '唐菁蔚', 'tangjingwei', '$2y$10$eWcufB2byZqOZspjH6UaO.4PKvivPpotPILxGL1LscJspy4a5t0VW', (SELECT id FROM sys_department WHERE name = '法务部'), (SELECT id FROM sys_post WHERE name = '法务'), 'ACTIVE' WHERE NOT EXISTS (SELECT 1 FROM sys_user WHERE account = 'tangjingwei');
INSERT INTO sys_user (job_no, name, account, password, department_id, post_id, status) SELECT 'HXJ032', '陈楠', 'chennan', '$2y$10$eWcufB2byZqOZspjH6UaO.4PKvivPpotPILxGL1LscJspy4a5t0VW', (SELECT id FROM sys_department WHERE name = '法务部'), (SELECT id FROM sys_post WHERE name = '法务主管'), 'ACTIVE' WHERE NOT EXISTS (SELECT 1 FROM sys_user WHERE account = 'chennan');
INSERT INTO sys_user (job_no, name, account, password, department_id, post_id, status) SELECT 'HXJ033', '朱铭骏', 'zhumingjun', '$2y$10$eWcufB2byZqOZspjH6UaO.4PKvivPpotPILxGL1LscJspy4a5t0VW', (SELECT id FROM sys_department WHERE name = '行政部'), (SELECT id FROM sys_post WHERE name = '行政专员'), 'ACTIVE' WHERE NOT EXISTS (SELECT 1 FROM sys_user WHERE account = 'zhumingjun');
INSERT INTO sys_user (job_no, name, account, password, department_id, post_id, status) SELECT 'HXJ034', '刘颖宁', 'liuyingning', '$2y$10$eWcufB2byZqOZspjH6UaO.4PKvivPpotPILxGL1LscJspy4a5t0VW', (SELECT id FROM sys_department WHERE name = '运营服务部'), (SELECT id FROM sys_post WHERE name = '商务专员'), 'ACTIVE' WHERE NOT EXISTS (SELECT 1 FROM sys_user WHERE account = 'liuyingning');
INSERT INTO sys_user (job_no, name, account, password, department_id, post_id, status) SELECT 'HXJ035', '杨淑欢', 'yangshuhuan', '$2y$10$eWcufB2byZqOZspjH6UaO.4PKvivPpotPILxGL1LscJspy4a5t0VW', (SELECT id FROM sys_department WHERE name = '运营服务部'), (SELECT id FROM sys_post WHERE name = '商务专员'), 'ACTIVE' WHERE NOT EXISTS (SELECT 1 FROM sys_user WHERE account = 'yangshuhuan');
INSERT INTO sys_user (job_no, name, account, password, department_id, post_id, status) SELECT 'HXJ036', '龚蓉', 'gongrong', '$2y$10$eWcufB2byZqOZspjH6UaO.4PKvivPpotPILxGL1LscJspy4a5t0VW', (SELECT id FROM sys_department WHERE name = '运营服务部'), (SELECT id FROM sys_post WHERE name = '商务专员'), 'ACTIVE' WHERE NOT EXISTS (SELECT 1 FROM sys_user WHERE account = 'gongrong');
INSERT INTO sys_user (job_no, name, account, password, department_id, post_id, status) SELECT 'HXJ037', '林丽婷', 'linliting', '$2y$10$eWcufB2byZqOZspjH6UaO.4PKvivPpotPILxGL1LscJspy4a5t0VW', (SELECT id FROM sys_department WHERE name = '资管中心'), (SELECT id FROM sys_post WHERE name = '出纳'), 'ACTIVE' WHERE NOT EXISTS (SELECT 1 FROM sys_user WHERE account = 'linliting');
INSERT INTO sys_user (job_no, name, account, password, department_id, post_id, status) SELECT 'HXJ038', '陈伟璇', 'chenweixuan', '$2y$10$eWcufB2byZqOZspjH6UaO.4PKvivPpotPILxGL1LscJspy4a5t0VW', (SELECT id FROM sys_department WHERE name = '资管中心'), (SELECT id FROM sys_post WHERE name = '出纳'), 'ACTIVE' WHERE NOT EXISTS (SELECT 1 FROM sys_user WHERE account = 'chenweixuan');
INSERT INTO sys_user (job_no, name, account, password, department_id, post_id, status) SELECT 'HXJ039', '沈盼静', 'shenpanjing', '$2y$10$eWcufB2byZqOZspjH6UaO.4PKvivPpotPILxGL1LscJspy4a5t0VW', (SELECT id FROM sys_department WHERE name = '资管中心'), (SELECT id FROM sys_post WHERE name = '出纳'), 'ACTIVE' WHERE NOT EXISTS (SELECT 1 FROM sys_user WHERE account = 'shenpanjing');
INSERT INTO sys_user (job_no, name, account, password, department_id, post_id, status) SELECT 'HXJ040', '李展仪', 'lizhanyi', '$2y$10$eWcufB2byZqOZspjH6UaO.4PKvivPpotPILxGL1LscJspy4a5t0VW', (SELECT id FROM sys_department WHERE name = '资管中心'), (SELECT id FROM sys_post WHERE name = '出纳'), 'ACTIVE' WHERE NOT EXISTS (SELECT 1 FROM sys_user WHERE account = 'lizhanyi');

-- ---------- 7. 人员角色关联（含 10 人多角色） ----------
INSERT INTO sys_user_role (user_id, role_id) SELECT u.id, r.id FROM sys_user u JOIN sys_role r ON r.name = '超级管理员' WHERE u.account = 'admin' AND NOT EXISTS (SELECT 1 FROM sys_user_role ur WHERE ur.user_id = u.id AND ur.role_id = r.id);
INSERT INTO sys_user_role (user_id, role_id) SELECT u.id, r.id FROM sys_user u JOIN sys_role r ON r.name = '超级管理员' WHERE u.account = 'linanran' AND NOT EXISTS (SELECT 1 FROM sys_user_role ur WHERE ur.user_id = u.id AND ur.role_id = r.id);
INSERT INTO sys_user_role (user_id, role_id) SELECT u.id, r.id FROM sys_user u JOIN sys_role r ON r.name = '公司领导' WHERE u.account = 'lianli' AND NOT EXISTS (SELECT 1 FROM sys_user_role ur WHERE ur.user_id = u.id AND ur.role_id = r.id);
INSERT INTO sys_user_role (user_id, role_id) SELECT u.id, r.id FROM sys_user u JOIN sys_role r ON r.name = '一级中心负责人' WHERE u.account = 'wangqiang' AND NOT EXISTS (SELECT 1 FROM sys_user_role ur WHERE ur.user_id = u.id AND ur.role_id = r.id);
INSERT INTO sys_user_role (user_id, role_id) SELECT u.id, r.id FROM sys_user u JOIN sys_role r ON r.name = '公司领导' WHERE u.account = 'wangqiang' AND NOT EXISTS (SELECT 1 FROM sys_user_role ur WHERE ur.user_id = u.id AND ur.role_id = r.id);
INSERT INTO sys_user_role (user_id, role_id) SELECT u.id, r.id FROM sys_user u JOIN sys_role r ON r.name = '执行总经理' WHERE u.account = 'wangqiang' AND NOT EXISTS (SELECT 1 FROM sys_user_role ur WHERE ur.user_id = u.id AND ur.role_id = r.id);
INSERT INTO sys_user_role (user_id, role_id) SELECT u.id, r.id FROM sys_user u JOIN sys_role r ON r.name = '一级中心负责人' WHERE u.account = 'shufei' AND NOT EXISTS (SELECT 1 FROM sys_user_role ur WHERE ur.user_id = u.id AND ur.role_id = r.id);
INSERT INTO sys_user_role (user_id, role_id) SELECT u.id, r.id FROM sys_user u JOIN sys_role r ON r.name = '二级部门负责人' WHERE u.account = 'shufei' AND NOT EXISTS (SELECT 1 FROM sys_user_role ur WHERE ur.user_id = u.id AND ur.role_id = r.id);
INSERT INTO sys_user_role (user_id, role_id) SELECT u.id, r.id FROM sys_user u JOIN sys_role r ON r.name = '一级中心负责人' WHERE u.account = 'luyifen' AND NOT EXISTS (SELECT 1 FROM sys_user_role ur WHERE ur.user_id = u.id AND ur.role_id = r.id);
INSERT INTO sys_user_role (user_id, role_id) SELECT u.id, r.id FROM sys_user u JOIN sys_role r ON r.name = '二级部门负责人' WHERE u.account = 'luyifen' AND NOT EXISTS (SELECT 1 FROM sys_user_role ur WHERE ur.user_id = u.id AND ur.role_id = r.id);
INSERT INTO sys_user_role (user_id, role_id) SELECT u.id, r.id FROM sys_user u JOIN sys_role r ON r.name = '一级中心负责人' WHERE u.account = 'liuting' AND NOT EXISTS (SELECT 1 FROM sys_user_role ur WHERE ur.user_id = u.id AND ur.role_id = r.id);
INSERT INTO sys_user_role (user_id, role_id) SELECT u.id, r.id FROM sys_user u JOIN sys_role r ON r.name = '二级部门负责人' WHERE u.account = 'liuting' AND NOT EXISTS (SELECT 1 FROM sys_user_role ur WHERE ur.user_id = u.id AND ur.role_id = r.id);
INSERT INTO sys_user_role (user_id, role_id) SELECT u.id, r.id FROM sys_user u JOIN sys_role r ON r.name = '出纳主管' WHERE u.account = 'liuting' AND NOT EXISTS (SELECT 1 FROM sys_user_role ur WHERE ur.user_id = u.id AND ur.role_id = r.id);
INSERT INTO sys_user_role (user_id, role_id) SELECT u.id, r.id FROM sys_user u JOIN sys_role r ON r.name = '一级中心负责人' WHERE u.account = 'wanghailiang' AND NOT EXISTS (SELECT 1 FROM sys_user_role ur WHERE ur.user_id = u.id AND ur.role_id = r.id);
INSERT INTO sys_user_role (user_id, role_id) SELECT u.id, r.id FROM sys_user u JOIN sys_role r ON r.name = '一级中心负责人' WHERE u.account = 'zhanglong' AND NOT EXISTS (SELECT 1 FROM sys_user_role ur WHERE ur.user_id = u.id AND ur.role_id = r.id);
INSERT INTO sys_user_role (user_id, role_id) SELECT u.id, r.id FROM sys_user u JOIN sys_role r ON r.name = '二级部门负责人' WHERE u.account = 'liujiahui' AND NOT EXISTS (SELECT 1 FROM sys_user_role ur WHERE ur.user_id = u.id AND ur.role_id = r.id);
INSERT INTO sys_user_role (user_id, role_id) SELECT u.id, r.id FROM sys_user u JOIN sys_role r ON r.name = '行政专员' WHERE u.account = 'liujiahui' AND NOT EXISTS (SELECT 1 FROM sys_user_role ur WHERE ur.user_id = u.id AND ur.role_id = r.id);
INSERT INTO sys_user_role (user_id, role_id) SELECT u.id, r.id FROM sys_user u JOIN sys_role r ON r.name = '行政主管' WHERE u.account = 'liujiahui' AND NOT EXISTS (SELECT 1 FROM sys_user_role ur WHERE ur.user_id = u.id AND ur.role_id = r.id);
INSERT INTO sys_user_role (user_id, role_id) SELECT u.id, r.id FROM sys_user u JOIN sys_role r ON r.name = '二级部门负责人' WHERE u.account = 'chenchenghui' AND NOT EXISTS (SELECT 1 FROM sys_user_role ur WHERE ur.user_id = u.id AND ur.role_id = r.id);
INSERT INTO sys_user_role (user_id, role_id) SELECT u.id, r.id FROM sys_user u JOIN sys_role r ON r.name = '二级部门负责人' WHERE u.account = 'guojingyu' AND NOT EXISTS (SELECT 1 FROM sys_user_role ur WHERE ur.user_id = u.id AND ur.role_id = r.id);
INSERT INTO sys_user_role (user_id, role_id) SELECT u.id, r.id FROM sys_user u JOIN sys_role r ON r.name = '二级部门负责人' WHERE u.account = 'wuhezhen' AND NOT EXISTS (SELECT 1 FROM sys_user_role ur WHERE ur.user_id = u.id AND ur.role_id = r.id);
INSERT INTO sys_user_role (user_id, role_id) SELECT u.id, r.id FROM sys_user u JOIN sys_role r ON r.name = '财务经理' WHERE u.account = 'wuhezhen' AND NOT EXISTS (SELECT 1 FROM sys_user_role ur WHERE ur.user_id = u.id AND ur.role_id = r.id);
INSERT INTO sys_user_role (user_id, role_id) SELECT u.id, r.id FROM sys_user u JOIN sys_role r ON r.name = '二级部门负责人' WHERE u.account = 'wangying' AND NOT EXISTS (SELECT 1 FROM sys_user_role ur WHERE ur.user_id = u.id AND ur.role_id = r.id);
INSERT INTO sys_user_role (user_id, role_id) SELECT u.id, r.id FROM sys_user u JOIN sys_role r ON r.name = '二级部门负责人' WHERE u.account = 'huangzhengzhe' AND NOT EXISTS (SELECT 1 FROM sys_user_role ur WHERE ur.user_id = u.id AND ur.role_id = r.id);
INSERT INTO sys_user_role (user_id, role_id) SELECT u.id, r.id FROM sys_user u JOIN sys_role r ON r.name = '运营服务主管' WHERE u.account = 'huangzhengzhe' AND NOT EXISTS (SELECT 1 FROM sys_user_role ur WHERE ur.user_id = u.id AND ur.role_id = r.id);
INSERT INTO sys_user_role (user_id, role_id) SELECT u.id, r.id FROM sys_user u JOIN sys_role r ON r.name = '二级部门负责人' WHERE u.account = 'lilinhua' AND NOT EXISTS (SELECT 1 FROM sys_user_role ur WHERE ur.user_id = u.id AND ur.role_id = r.id);
INSERT INTO sys_user_role (user_id, role_id) SELECT u.id, r.id FROM sys_user u JOIN sys_role r ON r.name = '二级部门负责人' WHERE u.account = 'miaofuxin' AND NOT EXISTS (SELECT 1 FROM sys_user_role ur WHERE ur.user_id = u.id AND ur.role_id = r.id);
INSERT INTO sys_user_role (user_id, role_id) SELECT u.id, r.id FROM sys_user u JOIN sys_role r ON r.name = '二级部门负责人' WHERE u.account = 'wengjianfa' AND NOT EXISTS (SELECT 1 FROM sys_user_role ur WHERE ur.user_id = u.id AND ur.role_id = r.id);
INSERT INTO sys_user_role (user_id, role_id) SELECT u.id, r.id FROM sys_user u JOIN sys_role r ON r.name = '会计主管&内控' WHERE u.account = 'wangyang' AND NOT EXISTS (SELECT 1 FROM sys_user_role ur WHERE ur.user_id = u.id AND ur.role_id = r.id);
INSERT INTO sys_user_role (user_id, role_id) SELECT u.id, r.id FROM sys_user u JOIN sys_role r ON r.name = '核算会计' WHERE u.account = 'wangyang' AND NOT EXISTS (SELECT 1 FROM sys_user_role ur WHERE ur.user_id = u.id AND ur.role_id = r.id);
INSERT INTO sys_user_role (user_id, role_id) SELECT u.id, r.id FROM sys_user u JOIN sys_role r ON r.name = '会计主管&内控' WHERE u.account = 'yaozhihao' AND NOT EXISTS (SELECT 1 FROM sys_user_role ur WHERE ur.user_id = u.id AND ur.role_id = r.id);
INSERT INTO sys_user_role (user_id, role_id) SELECT u.id, r.id FROM sys_user u JOIN sys_role r ON r.name = '核算会计' WHERE u.account = 'yaozhihao' AND NOT EXISTS (SELECT 1 FROM sys_user_role ur WHERE ur.user_id = u.id AND ur.role_id = r.id);
INSERT INTO sys_user_role (user_id, role_id) SELECT u.id, r.id FROM sys_user u JOIN sys_role r ON r.name = '会计主管&内控' WHERE u.account = 'wengtingting' AND NOT EXISTS (SELECT 1 FROM sys_user_role ur WHERE ur.user_id = u.id AND ur.role_id = r.id);
INSERT INTO sys_user_role (user_id, role_id) SELECT u.id, r.id FROM sys_user u JOIN sys_role r ON r.name = '出纳' WHERE u.account = 'wengtingting' AND NOT EXISTS (SELECT 1 FROM sys_user_role ur WHERE ur.user_id = u.id AND ur.role_id = r.id);
INSERT INTO sys_user_role (user_id, role_id) SELECT u.id, r.id FROM sys_user u JOIN sys_role r ON r.name = '核算会计' WHERE u.account = 'fengxunyi' AND NOT EXISTS (SELECT 1 FROM sys_user_role ur WHERE ur.user_id = u.id AND ur.role_id = r.id);
INSERT INTO sys_user_role (user_id, role_id) SELECT u.id, r.id FROM sys_user u JOIN sys_role r ON r.name = '核算会计' WHERE u.account = 'zhuyunyi' AND NOT EXISTS (SELECT 1 FROM sys_user_role ur WHERE ur.user_id = u.id AND ur.role_id = r.id);
INSERT INTO sys_user_role (user_id, role_id) SELECT u.id, r.id FROM sys_user u JOIN sys_role r ON r.name = '核算会计' WHERE u.account = 'shihuijun' AND NOT EXISTS (SELECT 1 FROM sys_user_role ur WHERE ur.user_id = u.id AND ur.role_id = r.id);
INSERT INTO sys_user_role (user_id, role_id) SELECT u.id, r.id FROM sys_user u JOIN sys_role r ON r.name = '核算会计' WHERE u.account = 'caicimian' AND NOT EXISTS (SELECT 1 FROM sys_user_role ur WHERE ur.user_id = u.id AND ur.role_id = r.id);
INSERT INTO sys_user_role (user_id, role_id) SELECT u.id, r.id FROM sys_user u JOIN sys_role r ON r.name = '核算会计' WHERE u.account = 'lixiaomei' AND NOT EXISTS (SELECT 1 FROM sys_user_role ur WHERE ur.user_id = u.id AND ur.role_id = r.id);
INSERT INTO sys_user_role (user_id, role_id) SELECT u.id, r.id FROM sys_user u JOIN sys_role r ON r.name = '核算会计' WHERE u.account = 'shihanwen' AND NOT EXISTS (SELECT 1 FROM sys_user_role ur WHERE ur.user_id = u.id AND ur.role_id = r.id);
INSERT INTO sys_user_role (user_id, role_id) SELECT u.id, r.id FROM sys_user u JOIN sys_role r ON r.name = '核算会计' WHERE u.account = 'zhangxinyi' AND NOT EXISTS (SELECT 1 FROM sys_user_role ur WHERE ur.user_id = u.id AND ur.role_id = r.id);
INSERT INTO sys_user_role (user_id, role_id) SELECT u.id, r.id FROM sys_user u JOIN sys_role r ON r.name = '核算会计' WHERE u.account = 'wenchaoqun' AND NOT EXISTS (SELECT 1 FROM sys_user_role ur WHERE ur.user_id = u.id AND ur.role_id = r.id);
INSERT INTO sys_user_role (user_id, role_id) SELECT u.id, r.id FROM sys_user u JOIN sys_role r ON r.name = '内控主管' WHERE u.account = 'sunqianqian' AND NOT EXISTS (SELECT 1 FROM sys_user_role ur WHERE ur.user_id = u.id AND ur.role_id = r.id);
INSERT INTO sys_user_role (user_id, role_id) SELECT u.id, r.id FROM sys_user u JOIN sys_role r ON r.name = '内控专员' WHERE u.account = 'zhengningjing' AND NOT EXISTS (SELECT 1 FROM sys_user_role ur WHERE ur.user_id = u.id AND ur.role_id = r.id);
INSERT INTO sys_user_role (user_id, role_id) SELECT u.id, r.id FROM sys_user u JOIN sys_role r ON r.name = '法务' WHERE u.account = 'tangjingwei' AND NOT EXISTS (SELECT 1 FROM sys_user_role ur WHERE ur.user_id = u.id AND ur.role_id = r.id);
INSERT INTO sys_user_role (user_id, role_id) SELECT u.id, r.id FROM sys_user u JOIN sys_role r ON r.name = '法务主管' WHERE u.account = 'chennan' AND NOT EXISTS (SELECT 1 FROM sys_user_role ur WHERE ur.user_id = u.id AND ur.role_id = r.id);
INSERT INTO sys_user_role (user_id, role_id) SELECT u.id, r.id FROM sys_user u JOIN sys_role r ON r.name = '行政专员' WHERE u.account = 'zhumingjun' AND NOT EXISTS (SELECT 1 FROM sys_user_role ur WHERE ur.user_id = u.id AND ur.role_id = r.id);
INSERT INTO sys_user_role (user_id, role_id) SELECT u.id, r.id FROM sys_user u JOIN sys_role r ON r.name = '商务专员' WHERE u.account = 'liuyingning' AND NOT EXISTS (SELECT 1 FROM sys_user_role ur WHERE ur.user_id = u.id AND ur.role_id = r.id);
INSERT INTO sys_user_role (user_id, role_id) SELECT u.id, r.id FROM sys_user u JOIN sys_role r ON r.name = '商务专员' WHERE u.account = 'yangshuhuan' AND NOT EXISTS (SELECT 1 FROM sys_user_role ur WHERE ur.user_id = u.id AND ur.role_id = r.id);
INSERT INTO sys_user_role (user_id, role_id) SELECT u.id, r.id FROM sys_user u JOIN sys_role r ON r.name = '商务专员' WHERE u.account = 'gongrong' AND NOT EXISTS (SELECT 1 FROM sys_user_role ur WHERE ur.user_id = u.id AND ur.role_id = r.id);
INSERT INTO sys_user_role (user_id, role_id) SELECT u.id, r.id FROM sys_user u JOIN sys_role r ON r.name = '出纳' WHERE u.account = 'linliting' AND NOT EXISTS (SELECT 1 FROM sys_user_role ur WHERE ur.user_id = u.id AND ur.role_id = r.id);
INSERT INTO sys_user_role (user_id, role_id) SELECT u.id, r.id FROM sys_user u JOIN sys_role r ON r.name = '出纳' WHERE u.account = 'chenweixuan' AND NOT EXISTS (SELECT 1 FROM sys_user_role ur WHERE ur.user_id = u.id AND ur.role_id = r.id);
INSERT INTO sys_user_role (user_id, role_id) SELECT u.id, r.id FROM sys_user u JOIN sys_role r ON r.name = '出纳' WHERE u.account = 'shenpanjing' AND NOT EXISTS (SELECT 1 FROM sys_user_role ur WHERE ur.user_id = u.id AND ur.role_id = r.id);
INSERT INTO sys_user_role (user_id, role_id) SELECT u.id, r.id FROM sys_user u JOIN sys_role r ON r.name = '出纳' WHERE u.account = 'lizhanyi' AND NOT EXISTS (SELECT 1 FROM sys_user_role ur WHERE ur.user_id = u.id AND ur.role_id = r.id);

-- ---------- 8. 汇报线（38 条，幂等 UPDATE） ----------
UPDATE sys_user SET manager_id = (SELECT t.id FROM (SELECT id FROM sys_user WHERE account = 'lianli') t) WHERE account = 'wangqiang' AND (manager_id IS NULL OR manager_id <> (SELECT t2.id FROM (SELECT id FROM sys_user WHERE account = 'lianli') t2));
UPDATE sys_user SET manager_id = (SELECT t.id FROM (SELECT id FROM sys_user WHERE account = 'wangqiang') t) WHERE account = 'shufei' AND (manager_id IS NULL OR manager_id <> (SELECT t2.id FROM (SELECT id FROM sys_user WHERE account = 'wangqiang') t2));
UPDATE sys_user SET manager_id = (SELECT t.id FROM (SELECT id FROM sys_user WHERE account = 'wangqiang') t) WHERE account = 'luyifen' AND (manager_id IS NULL OR manager_id <> (SELECT t2.id FROM (SELECT id FROM sys_user WHERE account = 'wangqiang') t2));
UPDATE sys_user SET manager_id = (SELECT t.id FROM (SELECT id FROM sys_user WHERE account = 'wangqiang') t) WHERE account = 'liuting' AND (manager_id IS NULL OR manager_id <> (SELECT t2.id FROM (SELECT id FROM sys_user WHERE account = 'wangqiang') t2));
UPDATE sys_user SET manager_id = (SELECT t.id FROM (SELECT id FROM sys_user WHERE account = 'wangqiang') t) WHERE account = 'wanghailiang' AND (manager_id IS NULL OR manager_id <> (SELECT t2.id FROM (SELECT id FROM sys_user WHERE account = 'wangqiang') t2));
UPDATE sys_user SET manager_id = (SELECT t.id FROM (SELECT id FROM sys_user WHERE account = 'wangqiang') t) WHERE account = 'zhanglong' AND (manager_id IS NULL OR manager_id <> (SELECT t2.id FROM (SELECT id FROM sys_user WHERE account = 'wangqiang') t2));
UPDATE sys_user SET manager_id = (SELECT t.id FROM (SELECT id FROM sys_user WHERE account = 'guojingyu') t) WHERE account = 'liujiahui' AND (manager_id IS NULL OR manager_id <> (SELECT t2.id FROM (SELECT id FROM sys_user WHERE account = 'guojingyu') t2));
UPDATE sys_user SET manager_id = (SELECT t.id FROM (SELECT id FROM sys_user WHERE account = 'wangqiang') t) WHERE account = 'chenchenghui' AND (manager_id IS NULL OR manager_id <> (SELECT t2.id FROM (SELECT id FROM sys_user WHERE account = 'wangqiang') t2));
UPDATE sys_user SET manager_id = (SELECT t.id FROM (SELECT id FROM sys_user WHERE account = 'luyifen') t) WHERE account = 'guojingyu' AND (manager_id IS NULL OR manager_id <> (SELECT t2.id FROM (SELECT id FROM sys_user WHERE account = 'luyifen') t2));
UPDATE sys_user SET manager_id = (SELECT t.id FROM (SELECT id FROM sys_user WHERE account = 'chenchenghui') t) WHERE account = 'wuhezhen' AND (manager_id IS NULL OR manager_id <> (SELECT t2.id FROM (SELECT id FROM sys_user WHERE account = 'chenchenghui') t2));
UPDATE sys_user SET manager_id = (SELECT t.id FROM (SELECT id FROM sys_user WHERE account = 'shufei') t) WHERE account = 'wangying' AND (manager_id IS NULL OR manager_id <> (SELECT t2.id FROM (SELECT id FROM sys_user WHERE account = 'shufei') t2));
UPDATE sys_user SET manager_id = (SELECT t.id FROM (SELECT id FROM sys_user WHERE account = 'wangying') t) WHERE account = 'huangzhengzhe' AND (manager_id IS NULL OR manager_id <> (SELECT t2.id FROM (SELECT id FROM sys_user WHERE account = 'wangying') t2));
UPDATE sys_user SET manager_id = (SELECT t.id FROM (SELECT id FROM sys_user WHERE account = 'wanghailiang') t) WHERE account = 'lilinhua' AND (manager_id IS NULL OR manager_id <> (SELECT t2.id FROM (SELECT id FROM sys_user WHERE account = 'wanghailiang') t2));
UPDATE sys_user SET manager_id = (SELECT t.id FROM (SELECT id FROM sys_user WHERE account = 'wangqiang') t) WHERE account = 'miaofuxin' AND (manager_id IS NULL OR manager_id <> (SELECT t2.id FROM (SELECT id FROM sys_user WHERE account = 'wangqiang') t2));
UPDATE sys_user SET manager_id = (SELECT t.id FROM (SELECT id FROM sys_user WHERE account = 'wangqiang') t) WHERE account = 'wengjianfa' AND (manager_id IS NULL OR manager_id <> (SELECT t2.id FROM (SELECT id FROM sys_user WHERE account = 'wangqiang') t2));
UPDATE sys_user SET manager_id = (SELECT t.id FROM (SELECT id FROM sys_user WHERE account = 'wangqiang') t) WHERE account = 'wangyang' AND (manager_id IS NULL OR manager_id <> (SELECT t2.id FROM (SELECT id FROM sys_user WHERE account = 'wangqiang') t2));
UPDATE sys_user SET manager_id = (SELECT t.id FROM (SELECT id FROM sys_user WHERE account = 'wangqiang') t) WHERE account = 'yaozhihao' AND (manager_id IS NULL OR manager_id <> (SELECT t2.id FROM (SELECT id FROM sys_user WHERE account = 'wangqiang') t2));
UPDATE sys_user SET manager_id = (SELECT t.id FROM (SELECT id FROM sys_user WHERE account = 'wangqiang') t) WHERE account = 'wengtingting' AND (manager_id IS NULL OR manager_id <> (SELECT t2.id FROM (SELECT id FROM sys_user WHERE account = 'wangqiang') t2));
UPDATE sys_user SET manager_id = (SELECT t.id FROM (SELECT id FROM sys_user WHERE account = 'wuhezhen') t) WHERE account = 'fengxunyi' AND (manager_id IS NULL OR manager_id <> (SELECT t2.id FROM (SELECT id FROM sys_user WHERE account = 'wuhezhen') t2));
UPDATE sys_user SET manager_id = (SELECT t.id FROM (SELECT id FROM sys_user WHERE account = 'wuhezhen') t) WHERE account = 'zhuyunyi' AND (manager_id IS NULL OR manager_id <> (SELECT t2.id FROM (SELECT id FROM sys_user WHERE account = 'wuhezhen') t2));
UPDATE sys_user SET manager_id = (SELECT t.id FROM (SELECT id FROM sys_user WHERE account = 'wuhezhen') t) WHERE account = 'shihuijun' AND (manager_id IS NULL OR manager_id <> (SELECT t2.id FROM (SELECT id FROM sys_user WHERE account = 'wuhezhen') t2));
UPDATE sys_user SET manager_id = (SELECT t.id FROM (SELECT id FROM sys_user WHERE account = 'wuhezhen') t) WHERE account = 'caicimian' AND (manager_id IS NULL OR manager_id <> (SELECT t2.id FROM (SELECT id FROM sys_user WHERE account = 'wuhezhen') t2));
UPDATE sys_user SET manager_id = (SELECT t.id FROM (SELECT id FROM sys_user WHERE account = 'wuhezhen') t) WHERE account = 'lixiaomei' AND (manager_id IS NULL OR manager_id <> (SELECT t2.id FROM (SELECT id FROM sys_user WHERE account = 'wuhezhen') t2));
UPDATE sys_user SET manager_id = (SELECT t.id FROM (SELECT id FROM sys_user WHERE account = 'wuhezhen') t) WHERE account = 'shihanwen' AND (manager_id IS NULL OR manager_id <> (SELECT t2.id FROM (SELECT id FROM sys_user WHERE account = 'wuhezhen') t2));
UPDATE sys_user SET manager_id = (SELECT t.id FROM (SELECT id FROM sys_user WHERE account = 'wuhezhen') t) WHERE account = 'zhangxinyi' AND (manager_id IS NULL OR manager_id <> (SELECT t2.id FROM (SELECT id FROM sys_user WHERE account = 'wuhezhen') t2));
UPDATE sys_user SET manager_id = (SELECT t.id FROM (SELECT id FROM sys_user WHERE account = 'wuhezhen') t) WHERE account = 'wenchaoqun' AND (manager_id IS NULL OR manager_id <> (SELECT t2.id FROM (SELECT id FROM sys_user WHERE account = 'wuhezhen') t2));
UPDATE sys_user SET manager_id = (SELECT t.id FROM (SELECT id FROM sys_user WHERE account = 'miaofuxin') t) WHERE account = 'sunqianqian' AND (manager_id IS NULL OR manager_id <> (SELECT t2.id FROM (SELECT id FROM sys_user WHERE account = 'miaofuxin') t2));
UPDATE sys_user SET manager_id = (SELECT t.id FROM (SELECT id FROM sys_user WHERE account = 'sunqianqian') t) WHERE account = 'zhengningjing' AND (manager_id IS NULL OR manager_id <> (SELECT t2.id FROM (SELECT id FROM sys_user WHERE account = 'sunqianqian') t2));
UPDATE sys_user SET manager_id = (SELECT t.id FROM (SELECT id FROM sys_user WHERE account = 'chennan') t) WHERE account = 'tangjingwei' AND (manager_id IS NULL OR manager_id <> (SELECT t2.id FROM (SELECT id FROM sys_user WHERE account = 'chennan') t2));
UPDATE sys_user SET manager_id = (SELECT t.id FROM (SELECT id FROM sys_user WHERE account = 'wengjianfa') t) WHERE account = 'chennan' AND (manager_id IS NULL OR manager_id <> (SELECT t2.id FROM (SELECT id FROM sys_user WHERE account = 'wengjianfa') t2));
UPDATE sys_user SET manager_id = (SELECT t.id FROM (SELECT id FROM sys_user WHERE account = 'liujiahui') t) WHERE account = 'zhumingjun' AND (manager_id IS NULL OR manager_id <> (SELECT t2.id FROM (SELECT id FROM sys_user WHERE account = 'liujiahui') t2));
UPDATE sys_user SET manager_id = (SELECT t.id FROM (SELECT id FROM sys_user WHERE account = 'huangzhengzhe') t) WHERE account = 'liuyingning' AND (manager_id IS NULL OR manager_id <> (SELECT t2.id FROM (SELECT id FROM sys_user WHERE account = 'huangzhengzhe') t2));
UPDATE sys_user SET manager_id = (SELECT t.id FROM (SELECT id FROM sys_user WHERE account = 'huangzhengzhe') t) WHERE account = 'yangshuhuan' AND (manager_id IS NULL OR manager_id <> (SELECT t2.id FROM (SELECT id FROM sys_user WHERE account = 'huangzhengzhe') t2));
UPDATE sys_user SET manager_id = (SELECT t.id FROM (SELECT id FROM sys_user WHERE account = 'huangzhengzhe') t) WHERE account = 'gongrong' AND (manager_id IS NULL OR manager_id <> (SELECT t2.id FROM (SELECT id FROM sys_user WHERE account = 'huangzhengzhe') t2));
UPDATE sys_user SET manager_id = (SELECT t.id FROM (SELECT id FROM sys_user WHERE account = 'liuting') t) WHERE account = 'linliting' AND (manager_id IS NULL OR manager_id <> (SELECT t2.id FROM (SELECT id FROM sys_user WHERE account = 'liuting') t2));
UPDATE sys_user SET manager_id = (SELECT t.id FROM (SELECT id FROM sys_user WHERE account = 'liuting') t) WHERE account = 'chenweixuan' AND (manager_id IS NULL OR manager_id <> (SELECT t2.id FROM (SELECT id FROM sys_user WHERE account = 'liuting') t2));
UPDATE sys_user SET manager_id = (SELECT t.id FROM (SELECT id FROM sys_user WHERE account = 'liuting') t) WHERE account = 'shenpanjing' AND (manager_id IS NULL OR manager_id <> (SELECT t2.id FROM (SELECT id FROM sys_user WHERE account = 'liuting') t2));
UPDATE sys_user SET manager_id = (SELECT t.id FROM (SELECT id FROM sys_user WHERE account = 'liuting') t) WHERE account = 'lizhanyi' AND (manager_id IS NULL OR manager_id <> (SELECT t2.id FROM (SELECT id FROM sys_user WHERE account = 'liuting') t2));

-- 完毕：幂等可重复执行
